### PR TITLE
Fix compile fail

### PR DESCRIPTION
**Pull request by 4kangjc**
- 将`cmake`中的`CMAKE_CXX_STANDARD`改为17和20，将会编译失败
- 本条PR修复`CMAKE_CXX_STANDARD`为17和20编译时的报错

### CODE REVIEW

**Comment by beef9999** [comment]
Looks good to me.

But I'm curious what was the OS you were running with? Some people have tried C++17 before and it could work.

**Comment by 4kangjc** [comment]
> Looks good to me.
> 
> But I'm curious what was the OS you were running with? Some people have tried C++17 before and it could work.

ArchLinux GCC12.2.0

**Comment by 4kangjc** [comment]
> > Looks good to me.
> > But I'm curious what was the OS you were running with? Some people have tried C++17 before and it could work.
> 
> ArchLinux GCC12.2.0

maybe need more CI

**Comment by 4kangjc** [comment]
应该是GCC12标准库头文件有变化，`filecopy.cpp`里的`free`需要`<cstdlib>`，`utils.cpp`里需要`std::string`

**Comment by 4kangjc** [comment]
`<cstdlib>`放错commit了

**Comment by 4kangjc** [comment]
have any other questions about this PR?

**Comment by 4kangjc** [comment]
**Reproducible using docker `gcc:12`**

Screenshot_20221205_195055
Screenshot_20221205_195228

**Comment by beef9999** [comment]
> have any other questions about this PR?

I'll have to cherry-pick your commit to the internal repo and then merge your PR. Please wait.

**Comment by beef9999** [comment]
Are you a employee of Alibaba?

**Comment by 4kangjc** [comment]
> Are you an employee of Alibaba?

No, I'm student

**Pull request merged**
